from tkinter import *
root=Tk()
def click(event):
    global var
    text = event.widget.cget("text")
    if text == "=":
        if var.get().isdigit():
            value = var = int(var)
        else:
            value = eval(var.get())
            var.set(value)
    elif text == 'AC':
        var.set("")
    elif text == "D":
        var.set(var.get()[:-1])
    else:
        var.set(var.get() + text)
    
root.geometry("450x900")
root.title("-CALCULATOR-")
root.wm_iconbitmap("icon.png")
var=StringVar()
var.set("")
ventry=Entry(root,textvariable=var,relief=SUNKEN,font="arial 20 bold")
ventry.pack(side=TOP,padx=20,pady=20,ipady=20,fill=X)
f1 =Frame(root,bg='grey')
f1.pack(side=TOP,fill=X,padx=20,pady=10)
b1= Button(f1 ,text="AC",bg='white',font="lucida 20 bold",borderwidth=5)
b1.pack(side=LEFT,padx=20,pady=20)
b1.bind("<Button-1>", click)
b2= Button(f1 ,text="%",bg='white',font="lucida 20 bold",borderwidth=5)
b2.pack(side=LEFT,padx=20,pady=20)
b2.bind("<Button-1>", click)
b3= Button(f1 ,text="/",bg='white',font="lucida 30 bold",borderwidth=5)
b3.pack(side=LEFT,padx=20,pady=20)
b3.bind("<Button-1>", click)
b4= Button(f1 ,text="D",bg='white',font="lucida 30 bold",borderwidth=5)
b4.pack(side=LEFT,padx=20,pady=20)
b4.bind("<Button-1>", click)

f2 =Frame(root,bg='grey')
f2.pack(side=TOP,fill=X,padx=20,pady=10)
b1= Button(f2 ,text="7",bg='white',font="lucida 30 bold",borderwidth=5)
b1.pack(side=LEFT,padx=20,pady=20)
b1.bind("<Button-1>", click)
b2= Button(f2 ,text="8",bg='white',font="lucida 30 bold",borderwidth=5)
b2.pack(side=LEFT,padx=20,pady=20)
b2.bind("<Button-1>", click)
b3= Button(f2 ,text="9",bg='white',font="lucida 30 bold",borderwidth=5)
b3.pack(side=LEFT,padx=20,pady=20)
b3.bind("<Button-1>", click)
b4= Button(f2 ,text="*",bg='white',font="lucida 30 bold",borderwidth=5)
b4.pack(side=LEFT,padx=20,pady=20)
b4.bind("<Button-1>", click)

f3 =Frame(root,bg='grey')
f3.pack(side=TOP,fill=X,padx=20,pady=10)
b1= Button(f3 ,text="4",bg='white',font="lucida 30 bold",borderwidth=5)
b1.pack(side=LEFT,padx=20,pady=20)
b1.bind("<Button-1>", click)
b2= Button(f3 ,text="5",bg='white',font="lucida 30 bold",borderwidth=5)
b2.pack(side=LEFT,padx=20,pady=20)
b2.bind("<Button-1>", click)
b3= Button(f3 ,text="6",bg='white',font="lucida 30 bold",borderwidth=5)
b3.pack(side=LEFT,padx=20,pady=20)
b3.bind("<Button-1>", click)
b4= Button(f3 ,text="-",bg='white',font="lucida 30 bold",borderwidth=5)
b4.pack(side=LEFT,padx=20,pady=20)
b4.bind("<Button-1>", click)

f4 =Frame(root,bg='grey')
f4.pack(side=TOP,fill=X,padx=20,pady=10)
b1= Button(f4 ,text="1",bg='white',font="lucida 30 bold",borderwidth=5)
b1.pack(side=LEFT,padx=20,pady=20)
b1.bind("<Button-1>", click)
b2= Button(f4 ,text="2",bg='white',font="lucida 30 bold",borderwidth=5)
b2.pack(side=LEFT,padx=20,pady=20)
b2.bind("<Button-1>", click)
b3= Button(f4 ,text="3",bg='white',font="lucida 30 bold",borderwidth=5)
b3.pack(side=LEFT,padx=20,pady=20)
b3.bind("<Button-1>", click)
b4= Button(f4 ,text="+",bg='white',font="lucida 30 bold",borderwidth=5)
b4.pack(side=LEFT,padx=20,pady=20)
b4.bind("<Button-1>", click)

f5 =Frame(root,bg='grey')
f5.pack(side=TOP,fill=X,padx=20,pady=10)
b1= Button(f5 ,text="00",bg='white',font="lucida 30 bold",borderwidth=5)
b1.pack(side=LEFT,padx=20,pady=20)
b1.bind("<Button-1>", click)
b2= Button(f5 ,text="0",bg='white',font="lucida 30 bold",borderwidth=5)
b2.pack(side=LEFT,padx=20,pady=20)
b2.bind("<Button-1>", click)
b3= Button(f5 ,text=".",bg='white',font="lucida 30 bold",borderwidth=5)
b3.pack(side=LEFT,padx=20,pady=20)
b3.bind("<Button-1>", click)
b4= Button(f5 ,text="=",bg='white',font="lucida 30 bold",borderwidth=5)
b4.pack(side=LEFT,padx=20,pady=20)
b4.bind("<Button-1>", click)

root.mainloop()